kill embedded
Splitit/Splitit.Plugins.Magento.V1 pull request #11
Opened 2020-11-25 12:02 UTC by AlexeySplitit

2020-11-25 19:15 UTC, sixg requested changes
Please remove fees completely

2020-11-25 19:15 UTC, sixg commented on app/code/community/PayItSimple/Payment/Model/Observer.php
> -				$storeId = Mage::app()->getStore()->getStoreId();
storeID is supposed to be used.

2020-11-25 19:15 UTC, sixg commented on app/code/community/PayItSimple/Payment/Model/PisPaymentFormMethod.php
> +		$params = $this->installmentplaninitParams($firstInstallmentAmount, $billAddress, $customerInfo, $cultureName);
why selectedInstallment is not passed. due to this we are facing issue on splitit page as more installments are showing up.

2020-11-25 19:15 UTC, sixg commented on app/code/community/PayItSimple/Payment/controllers/PaymentController.php
> -			$result = Mage::getSingleton("pis_payment/pisMethod")->installmentplaninit($api, $selectedInstallment);
selectedInstallment is required.

2020-11-25 19:15 UTC, sixg commented on app/code/community/PayItSimple/Payment/Model/Sales/Order/Total/Creditmemo/Fee.php
> +
remove fees completely

2020-11-25 19:15 UTC, sixg commented on app/code/community/PayItSimple/Payment/Model/Sales/Order/Total/Invoice/Fee.php
> +
remove fees completely

2020-11-25 19:15 UTC, sixg commented on app/code/community/PayItSimple/Payment/controllers/PaymentController.php
> -		$api = Mage::getSingleton("pis_payment/pisMethod")->_initApi($storeId = null);
this was required.

2020-11-26 07:45 UTC, AlexeySplitit commented on app/code/community/PayItSimple/Payment/Model/Observer.php
> -		$installments = array();
This variable is not used at all

2020-11-26 07:48 UTC, AlexeySplitit commented on app/code/community/PayItSimple/Payment/Model/Observer.php
> -		$installmentsInDropdown = array();
It has not been used in this method

2020-11-26 07:48 UTC, AlexeySplitit commented on app/code/community/PayItSimple/Payment/Model/Observer.php
> -	public function isSplititTextVisibleOnProduct($paymentMethod,$productId) {
Correct, will fix it

2020-11-26 07:51 UTC, AlexeySplitit commented on app/code/community/PayItSimple/Payment/Model/Observer.php
> -				$storeId = Mage::app()->getStore()->getStoreId();
You're almost correct. It was set to null in line below. Probably by mistake. Updated.

2020-11-26 07:56 UTC, AlexeySplitit commented on app/code/community/PayItSimple/Payment/Model/PisPaymentFormMethod.php
> +		$params = $this->installmentplaninitParams($firstInstallmentAmount, $billAddress, $customerInfo, $cultureName);
if you check installmentplaninitParams method, you will see that the line is commented where selectedInstallment variable is used, so this variable is not used. I'll restore it in case this fuctionality should be restored.

2020-11-26 08:00 UTC, AlexeySplitit commented on app/code/community/PayItSimple/Payment/Model/Sales/Order/Total/Invoice/Fee.php
> +
I removed only comment here. Do you want me to remove this class completely?

2020-11-26 08:00 UTC, AlexeySplitit commented on app/code/community/PayItSimple/Payment/Model/Sales/Order/Total/Creditmemo/Fee.php
> +
Do you want to remove this class completely? Only comment has been removed

2020-11-26 08:02 UTC, AlexeySplitit commented on app/code/community/PayItSimple/Payment/controllers/PaymentController.php
> -		$api = Mage::getSingleton("pis_payment/pisMethod")->_initApi($storeId = null);
Not exactly this, for payment form, updated the code, thanks

2020-11-26 08:06 UTC, AlexeySplitit commented on app/code/community/PayItSimple/Payment/controllers/PaymentController.php
> -			$result = Mage::getSingleton("pis_payment/pisMethod")->installmentplaninit($api, $selectedInstallment);
installmentplaninitForHostedSolution is used for payment form. I removed installmentplaninit, because it was called for CC. installmentplaninitForHostedSolution is not accepting $selectedInstallment, because on checkout you don't select anything.

2020-12-01 16:40 UTC, sixg commented on app/code/community/PayItSimple/Payment/Model/Sales/Order/Total/Creditmemo/Fee.php
> +
yes

2020-12-01 16:40 UTC, sixg commented on app/code/community/PayItSimple/Payment/Model/Sales/Order/Total/Invoice/Fee.php
> +
yes the whole fees module

2020-12-01 18:42 UTC, sixg commented on app/code/community/PayItSimple/Payment/Block/Adminhtml/System/Config/Form/Button.php
> +        elseif (strlen($code = Mage::getSingleton('adminhtml/config_data')->getWebsite())) // website level
can code compilation be done with these multi line comments changed to single line comments ?

2020-12-02 07:46 UTC, AlexeySplitit commented on app/code/community/PayItSimple/Payment/Block/Adminhtml/System/Config/Form/Button.php
> +        elseif (strlen($code = Mage::getSingleton('adminhtml/config_data')->getWebsite())) // website level
It's a comments, it doesn't affect a code compilation. There was a lot of similar code blocks and it worked

2020-12-14 18:51 UTC, merged